### ISSUE TITLE
"hiphen.png" absent in Letters Folder

### ISSUE THREAD

**Issue by Viswalahiri** [shrutiag14/Text-To-Handwrittens#2]
@shrutiag14 
I used a file from a lorem-ipsum generator that I found online.

After running the Flask app it said "hiphen.png" was not in the Letters folder.

Bug got fixed by adding this to said Letters folder and naming it as hiphen.png
![hiphen](https://user-images.githubusercontent.com/37129957/87580138-a32a4e00-c6f4-11ea-9f42-691bd0e86fb9.png)

**Comment by shrutiag14** [comment]
Okay.
